# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Pong/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Pong)

$(call add-radio-file-sha1-checked,radio/abl.img,9c4b163238ddcc3aae67d1551803f67d1f7670d9)
$(call add-radio-file-sha1-checked,radio/aop.img,7b393f76b73b3cdaf65a90284121d41c2afa6d11)
$(call add-radio-file-sha1-checked,radio/aop_config.img,b152f99c8c1cb338e15af31a5e737f07f39cdc0f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,eeafc6272375cf7558f354a05228d3342b590853)
$(call add-radio-file-sha1-checked,radio/cpucp.img,f004ec0d6a4087d49b94aa55a1787d3312e5c7a9)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c0c9df4115268cf97c9cef026ff1aed3add91230)
$(call add-radio-file-sha1-checked,radio/dsp.img,6e5cb80bf33ed5a585756db2241240de2cd371a8)
$(call add-radio-file-sha1-checked,radio/featenabler.img,cdf4ebf8690c9362cc47fd5c90752371db401afb)
$(call add-radio-file-sha1-checked,radio/hyp.img,37fc482c4d52eaea7e703dbfff3496f78ed48e8b)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f0091a51221a7c96d8b189b7e383b62bc83a28d9)
$(call add-radio-file-sha1-checked,radio/keymaster.img,2de3f842fab4668868b8f110b9768a2e7b5535af)
$(call add-radio-file-sha1-checked,radio/modem.img,afb899e91cebbf4bb37fced6c9f69df9640b9fc1)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,72e3b94165b349c55e4771032ec02f797ffe75d0)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,91dc0a65c3a872e533b8716d01bd1f5a2e652b10)
$(call add-radio-file-sha1-checked,radio/qupfw.img,37fb9f13426add7815293251e9132ccf2b544bdd)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,b467324d516c9266e155e14ff8794ceefd102358)
$(call add-radio-file-sha1-checked,radio/tz.img,08f80b21a154c15cc509cddb61d0a8508412023d)
$(call add-radio-file-sha1-checked,radio/uefi.img,e36539d72acb54f949565b644882dc9917e43506)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,a0a91fe7dedfae55cf92209cd029503b5937d46c)
$(call add-radio-file-sha1-checked,radio/xbl.img,a08ff8ce2afc6c29ff102e83e35abc157f74ca60)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,b07288acfee7e7f1da74ea5dd3f5c3a6882bdb23)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,38fde9b5460653a392e2373a1ab121b33de63653)

endif
