# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Pong/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Pong)

$(call add-radio-file-sha1-checked,radio/abl.img,ca0d62acf6ff1f74b39007bca50c1af03c12e782)
$(call add-radio-file-sha1-checked,radio/aop.img,7e5c4257f530a80bfc5c54fadf3009021dbe6dc1)
$(call add-radio-file-sha1-checked,radio/aop_config.img,8f94b3daeef54856b42b068e26eb3ec96f1e8c4f)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,f66c39d90cca8b7c3d0d29631e91063b5379ee72)
$(call add-radio-file-sha1-checked,radio/cpucp.img,381d76672f7a535b2325291abae79dd7647301c9)
$(call add-radio-file-sha1-checked,radio/devcfg.img,10379e9595469f382449fcb13e14337dbc340cde)
$(call add-radio-file-sha1-checked,radio/dsp.img,6e5cb80bf33ed5a585756db2241240de2cd371a8)
$(call add-radio-file-sha1-checked,radio/featenabler.img,3049d010cf242d44e7b859613c73731a9e40a9ac)
$(call add-radio-file-sha1-checked,radio/hyp.img,ef4ef1efd30c389eb653d7d760b1d9233e79da65)
$(call add-radio-file-sha1-checked,radio/imagefv.img,97d7c8a4a9146e3c5be4032a092b650322a887e9)
$(call add-radio-file-sha1-checked,radio/keymaster.img,2a5cb7a9a68ffdcb5d12ede90cb9be25f865d258)
$(call add-radio-file-sha1-checked,radio/modem.img,dd4ea20921fb37ea58b20b125dd001778a098c62)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,026396f3c523e767b177b23400488bd7a01c62e0)
$(call add-radio-file-sha1-checked,radio/multiimgqti.img,91dc0a65c3a872e533b8716d01bd1f5a2e652b10)
$(call add-radio-file-sha1-checked,radio/qupfw.img,5250fa0d242505dcff465c85973d6bff962ebbfb)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,f80ba5869bc1bc8f9064e77c1c2db38ece6b8c0e)
$(call add-radio-file-sha1-checked,radio/tz.img,6859072e88191e0601447ba107719b924abf123a)
$(call add-radio-file-sha1-checked,radio/uefi.img,a1810c7501323331a5c2536b1016a1cdf470c74d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,2d0af344b25d0b08999309c59b8d84a988f2f68e)
$(call add-radio-file-sha1-checked,radio/xbl.img,96c1b11e6a8d1f8cb3e3c17f43670f191b1b4f06)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,f4631551dffe24690dd98d508533ec2f3dd52ca0)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,fc68ecf8e6c25998969b66c6eaa085f5f2bbab33)

endif
